apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat3-ms-produtos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soat3-ms-produtos
  template:
    metadata:
      labels:
        app: soat3-ms-produtos
    spec:
      containers:
        - name: soat3-ms-produtos
          image: franciscosviana/soat3-ms-produtos:v1
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: produtos-config
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-produtos-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-produtos-secret
                  key: db_password
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-produtos-secret
                  key: db_root_password
          envFrom:
            - configMapRef:
                name: produtos-config
          resources:
            requests:
              cpu: 1500m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: soat3-ms-produtos-service
spec:
  type: NodePort
  selector:
    app: soat3-ms-produtos
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 32006
